# File: .pre-commit-config.yaml for Project Ekko
exclude: ^\.venv/ # Exclude the virtual environment directory
fail_fast: false # Run all checks even if one fails

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use latest stable tag
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=2048'] # Check for files larger than 2MB
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Use same version as pyproject.toml dev dependency if specified, or latest stable
    rev: v0.4.4 # Ensure consistency or use range/latest
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format